services:
  mosquitto:
    build:
      context: .
    image: mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    volumes:
      - ./log:/mosquitto/log
      - data:/mosquitto/data
volumes:
  data:
    name: "mosquitto_data"
