services:
  mosquitto:
    build:
      context: .
      args:
        IMG_VERSION: ${IMG_VERSION}
    image: my-mosquitto:${IMG_VERSION}
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - ${PORT:-1883}:1883
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/mosquitto/log
      - data:/mosquitto/data
networks:
  default:
    name: "mqtt_net"
volumes:
  data:
    name: "mosquitto_data"
