services:
  mosquitto:
    build:
      context: .
    image: dom-mosquitto:0.1
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - ${PORT:-1883}:1883
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./log:/mosquitto/log
      - data:/mosquitto/data
networks:
  default:
    name: "mosquitto_net"
volumes:
  data:
    name: "mosquitto_data"
